{% set name = "financedatabase" %}
{% set version = "2.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/financedatabase-{{ version }}.tar.gz
  sha256: 5e62648ba507e0ba2301328195439df1a30afffea9da6fca582fac5af30daf61

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.10,<3.13
    - setuptools <65.5.0
    - poetry-core >=1.0.0
    - pip
  run:
    - python >=3.10,<3.13
    - financetoolkit >=1.3.5,<2.0.0
    - pandas >=2.1.0,<3.0.0

test:
  imports:
    - financedatabase
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/JerBouma/FinanceDatabase
  summary: Database of equities, ETFs, funds, indices, currencies, cryptocurrencies, and money markets.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
