{% set python_min = '3.10' %}
{% set name = "financedatabase" %}
{% set version = "2.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/financedatabase-{{ version }}.tar.gz
  sha256: 9b1387cffe6e20a9b3d56612626361847a9c303470ecd3c3b90ad3cbd5f909d0

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools <65.5.0
    - poetry-core >=1.0.0
    - pip
  run:
    - python >={{ python_min }},<3.13
    - financetoolkit >=1.3.5,<2.0.0
    - pandas >=2.1.0,<3.0.0

test:
  imports:
    - financedatabase
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/JerBouma/FinanceDatabase
  summary: Database of equities, ETFs, funds, indices, currencies, cryptocurrencies, and money markets.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
