{% set python_min = "3.10" %}
{% set name = "financedatabase" %}
{% set version = "2.2.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/financedatabase-{{ version }}.tar.gz
  sha256: 5e3713032e8bdf20049d89ae0992af15e4214fab8b96087a83c2464f9f1670e3

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools <65.5.0
    - poetry-core >=1.0.0
    - pip
  run:
    - python >={{ python_min }},<3.13
    - financetoolkit >=1.3.5,<2.0.0
    - pandas >=2.1.0,<3.0.0

test:
  imports:
    - financedatabase
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/JerBouma/FinanceDatabase
  summary: Database of equities, ETFs, funds, indices, currencies, cryptocurrencies, and money markets.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
