schema_version: 1

context:
  name: financedatabase
  version: "2.4.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/financedatabase-${{ version }}.tar.gz
  sha256: a2af519e64e68baa52d369b49a8a16b09e77de0f20bb58e37243fbed225f2e87

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - pip
  run:
    - python >=${{ python_min }}
    - financetoolkit >=2.0.3,<3.0.0

tests:
  - python:
      imports:
        - financedatabase
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  summary: Database of equities, ETFs, funds, indices, currencies, cryptocurrencies, and money markets.
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/JerBouma/FinanceDatabase

extra:
  recipe-maintainers:
    - thewchan
